rust-lang-nursery/error-chain

README.md
src/lib.rs
src/quick_error.rs

I added two alternate implementations of the `error_chain` macro. One allows for an empty `types` block, the other leaves the `types` block out entirely. This should fix #5. I also ran rustfmt on lib.rs and quick_error.rs.

add alternate implementations of error_chain that do not require types section

---

src/lib.rs
tests/tests.rs

Fix #2.
One caveat to this is that it adds the type of the foreign error to the signature of the error-chain foreign_link_variant. As a result, the visibility of the foreign error type must be the same as the visibility of the error-chain type (public).

Forward Display implementation for foreign errors

---

src/lib.rs
tests/tests.rs

Fix #6 
Unfortunately, I wasn't able to come up with a simple way to match zero or one instances of a pattern. Because of this, it's possible to write a few pathological errors that will cause infinite recursion rather than a more helpful description.
Example:
```
#[test]
fn smoke_test_9() {
error_chain! {
types {
Error, ErrorKind, ChainErr, Result;
}
types {
Error, ErrorKind, ChainErr, Result;
}
foreign_links { }
errors {
HttpStatus(e: u32) {
description("http request returned an unsuccessful status code")
display("http request returned an unsuccessful status code: {}", e)
}
}
}
}
```
Because there are multiple `types` declarations, they are both combined into a single `types` declaration which looks like `types { Error, ErrorKind, ChainErr, Result; Error, ErrorKind, ChainErr, Result; …

Allow missing sections

---

README.md
src/lib.rs
tests/tests.rs

Rebase of https://github.com/brson/error-chain/pull/16. cc @cramertj .

Remove the foreign link description and forward to the foreign error

---

.travis.yml
tests/tests.rs

Apparently, if the macro invocation is the last "expression" in the function block, the parser expects an expression and will not let the macro expand to anything else.  Appending a semicolon will disabuse it of that notion.
The breakage only applies to error_chain! usage inside functions, which is probably not relevant other than in these tests.
Seems to be fixed in nightly 1.12 anyway.

Fix tests on stable/beta (closes #12)

---

src/lib.rs
tests/tests.rs

It is actually not a problem to have repeating instances of `links`,
`foreign_links` and `errors`, the items will just be appended.
To handle the zero-or-one rule for `types`, we can get away with just
one new matching rule, because there are three cases (no types, empty
types, and fully specified types).

Fixup matching, disallow repeating "types" (closes #23)

---

.travis.yml

Docs are still built (not uploaded) when untagged, but this might reveal bugs so I didn't change it.
I also don't have any means of testing this right now but I more or less copied from the travis docs so it is supposed to work.

only deploy docs when tagged (fix #18)

---

src/lib.rs
src/quick_error.rs
tests/tests.rs

```rust
#[cfg(unix)]
io::Error, Io;
```
would be better than
```rust
io::Error, Io, #[cfg(unix)];
```
, but it confuses the macro parser: `local ambiguity: multiple parsing options: built-in NTs path (link_error_path) or 1 other option.`

Allow conditional compilation for error variants.

---

CHANGELOG.md
src/lib.rs
src/quick_error.rs
tests/tests.rs

Instead of creating one trait at each macro invocation, we create it one time in
this crate. Bonus point: the trait in visible in the doc of `error-chain`.
TODO:
- doc
- Better name for ChainErr (trait and enum)
- add tests for chain_err

Move code from the macro to the crate

---

CHANGELOG.md
src/lib.rs
tests/tests.rs

This macro is similar to cargo's `bail!` and to the `throw` keyword originally proposed as part of the exception handling RFC. It's just a shorthand for early return with coercion.
I'm inclined to land this quick to sweeten up today's 0.7.0 release.
cc @Yamakaky @nikomatsakis

Add a `bail!` macro

---

src/lib.rs

Remove extraneous dot at end of link.
Signed-off-by: Andrew Donnellan <andrew@donnellan.id.au>

docs: fix link to quickstart.rs example

---

README.md

Same fix as 5d4114a56185 ("docs: fix link to quickstart.rs example").
Signed-off-by: Andrew Donnellan <andrew@donnellan.id.au>

README.md: fix link to quickstart example

---

examples/quickstart.rs
src/quick_main.rs

Use `stderr` to print error messages.

Print error messages to stderr in quickstart example

---

examples/all.rs

Part of the example used feature::Error instead of feature::ErrorKind,
which would have caused it to fail to compile if not for the fake
feature disabling it.

examples/all.rs: Fix typo in type name

---

.travis.yml
README.md
src/lib.rs

error_chain uses attributes on statements, stablized in Rust 1.13.
Factor them out of functions in the non-backtrace codepath, making it
possible to build a crate that uses error_chain with Rust 1.10.
The backtrace feature still requires Rust 1.13 for attributes on
statements, due to the impl_extract_backtrace macro, which needs to emit
a function with one block for each linked error type, some of which may
have attributes on them.  And any code using compile-time conditionals
in attributes on variants within an error_chain! invocation (which
includes many of the tests and examples) will produce an error due to
https://github.com/rust-lang/rust/issues/22250 (fixed in Rust 1.11).
But a crate using error_chain with default-features = false and avoiding
such compile-time conditionals will …

Make error_chain with default-features = false work with Rust 1.10

---

src/error_chain.rs

It's a bit odd that this tuple struct has:
* Documentation hidden on a member where the underlying type is not hidden.
* Number of elements and documentation count a bit off as when it was
hidden there were *two* hidden elements in the tuple struct signature
but the documentation text says there are *three* things in the
`Error`?
* The first hidden element of the tuple struct is used prominently in
the `lib.rs` documentation for pattern matching nested errors but it's
hidden. If it's to be consumed by users, documentation on it should
probably not be hidden. The `Error` tuple struct should be less opaque
here.

Clarify the documentation on the generated Error type and unhide ErrorKind element

---

CHANGELOG.md
src/lib.rs
src/quick_main.rs

The main function isn't the only place you might want to print the full
error message, for example, to log error messages produced by a handler
in a web server.

Add a method to format chained errors.

---

examples/quickstart.rs

closes #115 
This is one possible way to document the `display` method, giving the users of `quickstart.rs` the option to craft their own erorr message or use the builtin `display` method.

add documentation to quickstart about display

---

CHANGELOG.md
src/error_chain.rs
src/lib.rs
tests/tests.rs

from_err() chains another error as the cause of Error.
Another thing to consider is that currently the `Error::from_kind()` and `Error::form_err()` constructors take the kind directly. Since this is a ergonomics-oriented library, it might be reasonable to take `Into<ErrorKind>`? What do you think? Or will it cause inference problems again?

Implemented a new constructor for Error: from_err()

---

CHANGELOG.md
src/lib.rs
tests/tests.rs

This is quite trivial but is something I found myself defining in most of my crates (because you would always have some sort of kind of if-condition for `bail!` and quite often this condition is a trivial expression that does not affect the error kind/message, particularly so in i/o heavy blocks; less typing, less braces and less rightward-drift = win), so I figured I'd share as I think it fits the spirit of this crate quite well.
Basically,
```rust
ensure!(ultimate_answer == 42, "some {}", "error");
```

Add ensure! convenience macro

---

src/lib.rs
src/quick_error.rs
tests/tests.rs

This allows the following code to compile:
```
error_chain! {
links { }
foreign_links { }
errors {
HttpStatus(e: u32) {
description("http request returned an unsuccessful status code"),
display("http request returned an unsuccessful status code: {}", e),
}
}
};
```
(Note the comma after `description` and `display`)
This plays nicer with identation in at least the Emacs editor (and I think it should be easier to deal with for other editors as well)

Allow , after description/display/... in errors section

---

examples/quickstart.rs
src/lib.rs

Some documentation-only fixes to make the usage of linked and chained errors clearer, based on experience of some of our developers. Also fixes some broken references in docs.

Improve docs on linked and chained errors.

---

src/lib.rs

Hi - another proposed addition to the documentation, based on experience with our developers here. This is just a new section in the top-level docs, explaining how to get at the display, description, and backtrace of an error in your code.
Are you happy to add this? I know some of this is not error-chain-specific, but it seems like useful information alongside the other info on how to use the crate.
Thanks.

Add "Inspecting errors" section to top-level docs.

---

CHANGELOG.md
src/error_chain.rs
src/quick_error.rs

It's in order to make https://github.com/rust-lang/rust/pull/43009 build successfully.

Fix rustc build

---

src/lib.rs

Fixes #173 
I added a few links for std entries.  Also, considering #181, I didn't link to `ChainedError` unless necessary.

Add missing hyperlinks.

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

This became quite a large sed. Most (but not all of the links are handled by github redirect but I waned to be on the safe side and future proof).
Please let me know if I should reduce the scope of the rename. at least the Travis related links need to be changed.
fixes https://github.com/rust-lang-nursery/error-chain/issues/204

fixed broken links after move to rust-lang-nursery

---

.travis.yml
src/error_chain.rs
src/quick_error.rs

And deny warnings in CI
Fixes #208

Remove `unknown_lints` warning on stable

---

src/lib.rs

example for Backtrace::frames

---

CHANGELOG.md
src/error_chain.rs

Fixes #185 
Just hides the macro and updates documentation to not mention it.

Hide error_chain_processed macro from docs

---

Cargo.toml
examples/size.rs
src/backtrace.rs
src/error_chain.rs
src/lib.rs

* Only call `env::var_os` once, cache the result in a global
* Move backtrace-related cfg code to one location, avoids `#[cfg]` traffic
* Don't resolve backtraces until they're displayed

Improve handling of backtraces

---

src/error_chain.rs
src/impl_error_chain_kind.rs
src/lib.rs

Builds on @hoodie's work in #246 to allow both `unused_doc_comment` and `unused_doc_comments` in a fully back-compatible fashion.
Fixes #245

Fix new renamed_and_removed_lints warning

---

.travis.yml
Cargo.toml
build.rs
src/backtrace.rs
src/error_chain.rs
src/lib.rs
tests/tests.rs

Use Error::source not Error::cause in Rust versions that have it

---

src/error_chain.rs
src/impl_error_chain_kind.rs
src/lib.rs

Fixes #250 
Uses the same approach as described here to make macros usable in both the new and old way of importing them: https://users.rust-lang.org/t/2018-edition-macro-ergonomics/18790
Issue #250 has become more of a problem now when Rust 1.30 is out and the new way of importing macros is out on the stable channel. Would be really good to have this, or a variant of this, merged and a 0.12.1 patch release published.

Fix new macro import style

---

README.md

Note that the custom license shield is needed as Github doesn't properly identify dual-licenses

Correct Travis paths, and add custom license shield

---

src/error_chain.rs
src/lib.rs
tests/tests.rs

While the `Msg` variant may be a useful option for some users, many will
prefer to stick to more descriptive error types, and won't want this
variant present. This allows a `skip_msg_variant` flag to be passed to
`error_chain!`, which will cause no `Msg` variant to be present in the
generated code.
I've also refactored the body of `impl_error_chain_processing` to not
care about the number of arguments other than the final branch, so more
cases can be added in the future without having to touch as many places
as I did.
Fixes #200.

Allow skipping the `Msg` variant

---

src/error_chain.rs
src/impl_error_chain_kind.rs

I think that the following modification (seen in quick-error) could work here, to fix issue #251.
I splitted the problematic part in two parts:
1. ignore unknown/renamed/removed lints
2. disable warnings about unused doc comments

try to fix issue #251

---

src/error_chain.rs
src/lib.rs
tests/tests.rs

bare_trait_objects for  deprecations

---

.travis.yml

Backtrace has errors < 1.30

---

.travis.yml
src/lib.rs

Minimum supported rust is now 1.13.0 (without backtrace support)
Minimum supported rust is now 1.32 with backtrace support (see backtrace-rs)
Explicitly call ChainedError::backtrace()

Resolve failing tests

---

build.rs
src/error_chain.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon (1.42)
This PR:
- adds configuration options: `has_error_description_deprecated`
- implements Error::description conditionally
- create a conditional macro `impl_error_chain_kind` without  usage of `Error::description`
Related PR: https://github.com/rust-lang/rust/pull/66919
Alternative PR(with removed description): https://github.com/rust-lang-nursery/error-chain/pull/283

Use Error::description only for rust below 1.42

---

.travis.yml
tests/tests.rs

#280 reformatted things, but without explicit work it'll drift out of line again. This PR checks that.

Check formatting on code at build time

---

CHANGELOG.md
Cargo.toml
src/lib.rs

version 0.12.3 file executable bits were set during the changelog updates, reverting the change.  Version 0.12.4 is another attempt at 0.12.3's mission

version 0.12.4
